[package]
name = "todo"
version = "0.1.0"
authors = ["thekuwayama <thekuwayama@gmail.com>"]
description = "todo"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
regex = "1.4"
chrono = { version = "0.4", features = ["unstable-locales"] }
